### ISSUE TITLE
Beta Roadmap

### ISSUE THREAD

**Issue by Asoul** [stelelab/stele#1]
# Beta Roadmap

## 0.0.1
- [x] A versioning static website via Github
- [x] A smart contract for post
- [x] Can create post

## 0.0.2
- [x] Connect javascript library to eth mainnet
- [x] Can view post in website

## 0.0.3
- [x] Can create post in website
- [x] Pagination (use infinite scroll)

**Comment by Asoul** [comment]
- [x] Scroll to load more (pagination)
- [x] Fix scroll to load more when scroll fast

**Comment by Asoul** [comment]
- [x] Creator username

**Comment by Asoul** [comment]
- [x] Add og information

**Comment by Asoul** [comment]
- [x] Add a logo and favicon

**Comment by Asoul** [comment]
- [x] A page for user posts

**Comment by Asoul** [comment]
# Other pages
- [x] user page
- [x] post page

# Features
~~- [ ] share to twitter, facebook, etc.~~ Move to #2 
~~- [ ] hashtag~~ Move to #5 
- [x] user infotmation
~~- [ ] comment~~ Move to #6 
- [x] reaction

**Comment by Asoul** [comment]
- [x] Set username

**Comment by Asoul** [comment]
- [x] Add loading event

**Comment by Asoul** [comment]
~~- [ ] Pagination for user page~~
Create another issue already

**Comment by Asoul** [comment]
- [x] Strip long address in mobile? wrap for long address

**Comment by Asoul** [comment]
- [x] iPhone + Safari sometimes cache user & post page

**Comment by Asoul** [comment]
- [x] Set description

**Comment by Asoul** [comment]
~~- [ ] SEO Optimise for user/post page~~

Seems no way to do on client side, it's server side work

**Comment by Asoul** [comment]
- [x] custom 404 page

**Comment by Asoul** [comment]
- [x] Add message popup for tips

**Comment by Asoul** [comment]
- [x] About page

**Comment by Asoul** [comment]
~~- [ ] Github issue template~~ Move to #7
~~- [ ] Github contribute guide~~ Move to #8

**Comment by Asoul** [comment]
~~- [ ] Authorized account~~ Move to #9

**Comment by Asoul** [comment]
~~- [ ] Show like status for user~~ Move to #10

**Comment by Asoul** [comment]
~~- [ ] username restriction~~ Move to #11

**Comment by Asoul** [comment]
Beta version has released, move undo tasks into another issues
